### PR TITLE
Chore  add get languages method

### LINKED ISSUE #12: Add missing method getLanguages()
Add the missing method getLanguages() that will return all local available languages.

Basically it will return the keys of `languages` object in index.js file: https://github.com/NodeSecure/i18n/blob/main/index.js#L7

Please also update `index.d.ts` and add test.

### PR DESCRIPTION
**Pull request by Kawacrepe**
Close #12 

+ fix setLocalLang which does not worked as expected because we don't set our constant.LANG_UPDATE value at true once cacache update.

### CODE REVIEW

**Comment by fraxken** [comment]
@Kawacrepe Il faudrait aussi mettre à jour le README.md

**Review by tony-go — APPROVED** [review]
Neat!

**Comment by tony-go** [comment]
> @Kawacrepe You should also update the README

With that ^^

**Review by fraxken — APPROVED** [review]

**Comment by fraxken** [comment]
@all-contributors please add @Kawacrepe for code, docs

**Pull request merged**
